Updated my_neuron_model.py
SpiNNakerManchester/SpyNNakerNewModelTemplate_OLD pull request #3
Opened 2017-02-26 01:26 UTC by J-KC-Man

Updated def get_n_global_parameters(self) to return 3 parameters instead of 1 to prevent the following error when running example.py:

2017-02-26 00:50:42 ERROR: Error executing data specification for 0, 0, 2
Traceback (most recent call last):
…
data_specification.exceptions.DataSpecificationNoMoreException: Space unavailable to write all the elements requested by the write operation. Space available: 0; space requested: 4 for region 1.

2017-02-26 01:38 UTC, J-KC-Man commented
Also updated my_threshold_type.py:

Updated def get_n_threshold_parameters(self) to return 2 parameters instead of 1 to prevent the following error when running example.py:

2017-02-26 00:50:42 ERROR: Error executing data specification for 0, 0, 2
Traceback (most recent call last):
…
data_specification.exceptions.DataSpecificationNoMoreException: Space unavailable to write all the elements requested by the write operation. Space available: 0; space requested: 4 for region 1.

2017-06-30 16:35 UTC, rowleya requested changes

2017-06-30 16:35 UTC, rowleya commented on python_models/neuron/neuron_models/my_neuron_model.py
> +        return 3
Don't think this is right - there is only one global parameter that I can see

2017-07-03 09:20 UTC, andrewgait commented on python_models/neuron/neuron_models/my_neuron_model.py
> +        return 3
I agree with @rowleya - there's only one global parameter here; there are 3 neural parameters, which is where the confusion may have arisen.

The other threshold_type error (there are 2 parameters in my_threshold_type, as Justin says) was fixed when we moved on from sPyNNakerNewModelTemplate to separate versions for PyNN 0.7 (sPyNNaker7NewModelTemplate) and PyNN 0.8 (sPyNNaker8NewModelTemplate).  We shouldn't be using sPyNNakerNewModelTemplate any more...

2017-07-03 10:06 UTC, rowleya commented
Closing this - as Andrew points out, this is now fixed in another module.

2017-07-03 10:06 UTC, closed without merging